apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  namespace: develop
  labels:
    app: app
    env: dev
spec:
  containers:
  - name: app
    image: nginx:1.22.0
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    ports:
      - containerPort: 80
        name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: develop
  labels:
    app: app
    env: dev
spec:
  selector:
    app: app
  ports:
  - name: app
    protocol: TCP
    port: 80
    targetPort: http-web-svc